databases:
  - name: sueweetstay-db
    plan: free
    databaseName: sueweetbnb
    user: sueweetbnb

services:
  - type: web
    plan: free
    name: sueweetstay-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sueweetstay-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
