# Generated by Django 5.2 on 2025-04-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_profile_photo_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="currency",
            field=models.CharField(
                choices=[("won", "KRW"), ("usd", "Dollar")], max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("kr", "Korea"), ("en", "English")], max_length=2
            ),
        ),
    ]
