# Generated by Django 5.2 on 2025-04-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "experiences",
            "0003_alter_experience_category_alter_experience_host_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="city",
            field=models.CharField(default="Gold Coast", max_length=80),
        ),
        migrations.AlterField(
            model_name="experience",
            name="country",
            field=models.CharField(default="Australia", max_length=50),
        ),
    ]
